"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['MainWindow.py', 'tcpclient.py', 'deviceinfo.py','tcpserver.py', 'tools.py']

OPTIONS = { 'includes': ['PyQt5.QtWidgets', 'PyQt5.QtCore', 'deviceinfo', 'tcpserver'],}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
